### ISSUE TITLE
Берёт только первую строчку от каждой цитаты

### ISSUE THREAD

**Issue by illus0r** [aruseni/bash.im-parser#1]
Привет! Я хотел и визуализировать данные баша, твой скрипт — то что надо. Но парсит он только первые строчки.

Пример:
```
sqlite> select * from quotes where id="445393";
445393|Я: А ты это где-нибудь на мамском форуме спроси.|1497955500
sqlite>
```
хотя в оригинале 

![image](https://user-images.githubusercontent.com/797993/27418032-30701106-5721-11e7-919a-9d29e098df45.png)

**Comment by aruseni** [comment]
О, прикольно, значит, они как-то поменяли вёрстку. Я посмотрю.

**Comment by aruseni** [comment]
Да нет, работает всё.

    >>> print db.cursor().execute("select * from quotes where id=445393").fetchone()[1]
    Я: А ты это где-нибудь на мамском форуме спроси.
    ххх: Меня на трёх мамкофорумах ещё при первом ребёнке забанили.
    ххх: Всех трёх случаев не помню - помню самое эпохальное: одна спросила, что делать, если ребёночек ничего не кушает. Дык я ей с высоты собственного опыта честно выдала: на первые 17 лет забить и смириться, а дальше отправить учиться в другой город и бабла высылать ровно на трамвай и макароны без никто. Гарантировано, что уже в первый приезд домой кушать ребёночек будет хоть с помойного ведра. Бан-с.

Мне, правда, не очень нравится, что два переноса строки как один сохраняются. Это сейчас поменяю.

**Comment by illus0r** [comment]
Спасибо! Я заметил, что некоторые цитаты у меня многострочные:
```
sqlite> select * from quotes where id="33";
33|* Криста61109 говорит трагическим голосом
<Криста61109> bf? e ytuj ; ntktajy gjzdbkcz///|1093881060
```

То ли питон выводит больше информации, чем консоль sqlite3, то ли в моей таблице некоторые записи всё-таки однострочные.

Хотел попробовать читать БД питоном, но получилось быстро установить либы. Можешь проверить мой файл?
[quotes.sqlite3.zip](https://github.com/aruseni/bash.im-parser/files/1100511/quotes.sqlite3.zip)

**Comment by aruseni** [comment]
А не нужны либы, sqlite [в стандартной библиотеке](https://docs.python.org/3/library/sqlite3.html). Но в твоём файле действительно цитата 445393 неправильно сохранена, там только первая строчка. Попробуй опять распарсить.

**Comment by illus0r** [comment]
Перепарсил, опять некоторые цитаты в одну строку. Может быть, дело в парсере? Вот что в консоли:
```
➜  bash.im-parser git:(master) ✗ ./parse.py 1 1267
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 124 of the file ./parse.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
```

То есть он парсит `html.parser`ом. А какой у тебя парсер?

**Comment by aruseni** [comment]
А ты не сделал pull. Там сейчас явно указан парсер.
